# Generated by Django 6.0.3 on 2026-03-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        ("environments", "0001_initial"),
        ("mitre", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttackChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_ip", models.GenericIPAddressField()),
                (
                    "chain_type",
                    models.CharField(
                        choices=[
                            ("recon_to_exploit", "Recon to Exploit"),
                            ("scan_to_brute", "Scan to Brute Force"),
                            ("dos_campaign", "DoS Campaign"),
                            ("multi_stage", "Multi-Stage"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("risk_score", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("resolved", "Resolved")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "alerts",
                    models.ManyToManyField(
                        blank=True, related_name="attack_chains", to="alerts.alert"
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attack_chains",
                        to="environments.environment",
                    ),
                ),
                (
                    "mitre_techniques",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attack_chains",
                        to="mitre.mitretechnique",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentRiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="environments.environment",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
            },
        ),
    ]
