stateDiagram-v2
    [*] --> Unassigned
    Unassigned --> Assigned : Assign to member
    Assigned --> Reassigned : Change assignee
    Reassigned --> Assigned
    Assigned --> StatusUpdated : Change status
    StatusUpdated --> [*]