# Generated by Django 6.0.3 on 2026-03-06 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_ip", models.GenericIPAddressField()),
                ("dst_ip", models.GenericIPAddressField()),
                ("src_port", models.IntegerField(blank=True, null=True)),
                ("dst_port", models.IntegerField(blank=True, null=True)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("TCP", "TCP"),
                            ("UDP", "UDP"),
                            ("ICMP", "ICMP"),
                            ("HTTP", "HTTP"),
                            ("DNS", "DNS"),
                            ("SSH", "SSH"),
                            ("FTP", "FTP"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("port_scan", "Port Scan"),
                            ("dos", "Denial of Service"),
                            ("brute_force", "Brute Force"),
                            ("sql_injection", "SQL Injection"),
                            ("xss", "Cross-Site Scripting"),
                            ("protocol_anomaly", "Protocol Anomaly"),
                            ("suspicious_ip", "Suspicious IP"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Confidence score between 0 and 1."),
                ),
                ("raw_payload", models.TextField(blank=True, default="")),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ml_model_used",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mitre_tactic",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mitre_technique_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="environments.environment",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("reason", models.TextField()),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                ("unblocked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_ips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_ips",
                        to="environments.environment",
                    ),
                ),
            ],
            options={
                "ordering": ["-blocked_at"],
            },
        ),
    ]
