# Generated by Django 6.0.3 on 2026-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_logupload_trafficfilterrule_whitelistedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficfilterrule',
            name='threshold_count',
            field=models.IntegerField(blank=True, help_text='Number of events to trigger (e.g., 500 requests).', null=True),
        ),
        migrations.AddField(
            model_name='trafficfilterrule',
            name='threshold_window_seconds',
            field=models.IntegerField(blank=True, help_text='Time window in seconds (e.g., 60 for per-minute).', null=True),
        ),
        migrations.AddField(
            model_name='trafficfilterrule',
            name='traffic_category',
            field=models.CharField(blank=True, choices=[('volume', 'Volume-based'), ('login', 'Login-based'), ('domain', 'Domain-based'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='trafficfilterrule',
            name='action',
            field=models.CharField(choices=[('suppress', 'Suppress'), ('highlight', 'Highlight'), ('auto_block', 'Auto Block'), ('alert_only', 'Alert Only'), ('auto_block_timed', 'Auto-Block for 1 Hour')], max_length=20),
        ),
    ]
