# Generated by Django 6.0.3 on 2026-03-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MitreTactic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tactic_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["tactic_id"],
            },
        ),
        migrations.CreateModel(
            name="MitreTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technique_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("detection_hint", models.TextField(blank=True, null=True)),
                ("mitigation", models.TextField(blank=True, null=True)),
                ("maps_to_alert_types", models.JSONField(blank=True, default=list)),
                (
                    "tactic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="techniques",
                        to="mitre.mitretactic",
                    ),
                ),
            ],
            options={
                "ordering": ["technique_id"],
            },
        ),
    ]
