# Generated by Django 6.0.3 on 2026-03-06 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptureSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interface", models.CharField(max_length=50)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("packets_captured", models.IntegerField(default=0)),
                ("alerts_generated", models.IntegerField(default=0)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_sessions",
                        to="environments.environment",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="NetworkFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("src_ip", models.GenericIPAddressField()),
                ("dst_ip", models.GenericIPAddressField()),
                ("src_port", models.IntegerField(blank=True, null=True)),
                ("dst_port", models.IntegerField(blank=True, null=True)),
                ("protocol", models.CharField(max_length=10)),
                ("packet_length", models.IntegerField()),
                ("ttl", models.IntegerField()),
                ("flags", models.CharField(blank=True, default="", max_length=50)),
                ("inter_arrival_time", models.FloatField(blank=True, null=True)),
                ("features_json", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="network_capture.capturesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
