# Generated by Django 6.0.3 on 2026-03-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("random_forest", "Random Forest"),
                            ("svm", "SVM"),
                            ("isolation_forest", "Isolation Forest"),
                            ("neural_net", "Neural Network"),
                        ],
                        default="random_forest",
                        max_length=20,
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("detection_threshold", models.FloatField(default=0.5)),
                ("alert_threshold", models.JSONField(blank=True, default=dict)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "model_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "environment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_config",
                        to="environments.environment",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Model Config",
                "verbose_name_plural": "ML Model Configs",
            },
        ),
        migrations.CreateModel(
            name="MLModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("training_samples", models.IntegerField()),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="ml_engine.mlmodelconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Model Metrics",
                "verbose_name_plural": "ML Model Metrics",
                "ordering": ["-evaluated_at"],
            },
        ),
    ]
