# Generated by Django 6.0.3 on 2026-03-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThreatIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("threat_type", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=200)),
                (
                    "confidence",
                    models.FloatField(help_text="Confidence score between 0 and 1."),
                ),
                ("last_seen", models.DateTimeField()),
                ("description", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "mitre_tactic",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "mitre_technique",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "mitre_technique_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Threat Intelligence",
                "verbose_name_plural": "Threat Intelligence",
                "ordering": ["-last_seen"],
            },
        ),
    ]
